### PR TITLE
Add before and after scenario and step hook messages

### PR DESCRIPTION
**Pull request by henriheimann**
Solution as described in https://github.com/getgauge-contrib/json-report/issues/18. Adds pre and post hook messages to scenarios and steps.

### CODE REVIEW

**Review by sriv — DISMISSED** [review]

**Comment by sriv** [comment]
Thanks for the PR @henriheimann 

I see that you've included the step and scenario hook mesaages. Gauge allows you to add mesaages in spec and suite hooks as well.

I am happy to merge this as it.is, but wanted to check if you'd like yo explore other hooks as well?

Also, could you please sign your commit? Please see https://github.com/getgauge-contrib/json-report/pull/21/checks?check_run_id=2840155658

**Comment by henriheimann** [comment]
Good point, I'll take a minute and add the spec and suite hooks as well. And sign off the commits :)

**Comment by henriheimann** [comment]
Done!

**Review by sriv — APPROVED** [review]

**Comment by sriv** [comment]
Thanks again @henriheimann , I'll make a release soon

**Comment by henriheimann** [comment]
Hey @sriv, just a quick follow up. Could you release 0.3.6 anytime soon, so we can update our local installations of the plugin? That would be really helpful. Thanks a lot in advance!

**Comment by sriv** [comment]
Thanks for reminding and apologies for not following this up.

As it happened, I did schedule a release, and the scripts ran (https://github.com/getgauge-contrib/json-report/actions/runs/943735426). I assumed the release would have gone through, but it ended up in draft state! - https://github.com/getgauge-contrib/json-report/releases/tag/untagged-ae96913f9907daf0f8a9

I'll make the release right away

**Comment by sriv** [comment]
The release has been made - https://github.com/getgauge-contrib/json-report/releases/tag/v0.3.6

Please note that it will take about 12 hours for the cache to refresh and then you should be able to install this release via `gauge install json-report` command.

**Pull request merged**
